artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://github.com/DivyanshuJhanwar/Dataset_Extraction_Hub/raw/main/books_dataset.zip
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data